GET http://localhost:8000/api/products/list
Content-Type: application/json

###
POST http://localhost:8000/api/products/save
Content-Type: application/json

{
    "name": "oreo",
    "lastname": "ramos",
    "age": 25
}
###
PUT http://localhost:8000/api/products/update/1
Content-Type: application/json

{
    "id": 4,
    "name": "Juan",
    "lastname": "Perez",
    "age": 36
}
###
DELETE  http://localhost:8000/api/products/delete/5
Content-Type: application/json

{
    "id": 5,
    "name": "Juan",
    "lastname": "Perez",
    "age": 36
}